version: '3.8'

services:
  postgres:
    container_name: db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: java
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
    ports:
      - '5433:5432'

  backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/java
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1
